# fly.toml app configuration file generated for redux-anecdotes on 2023-08-29T12:01:24+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "redux-anecdotes"
primary_region = "arn"

# [deploy]
    # release_command = "yarn run build"

[processes]
    app = "yarn run start:prod"
    server = "yarn run server"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app", "server"]
